export {default as Dashboard} from "./Dashboard"
export {default as Home} from "./Home"
export {default as GalleryAdmin} from "./Gallery"
export {default as Identity} from "./Identity"
export {default as Partner} from "./Partner"
export {default as Program} from "./Program"
export {default as Team} from "./Team"